# theme = "coder" # set the theme
theme = "hugo-theme-console"
title = "Carson Drake"
googleAnalytics = "UA-48292614-1"

[params] # theme parameters
    author = "Carson Drake" # author's name
    info = "Problem Solver & Technology Consultant" # author's job title or info
    description = "Carson's personal site." # site description
    keywords = "technology,developer,consultant" # site keywords
    
    
    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true
    
# Social links
#[[params.social]]
#   name = "Github"
#   weight = 1
#   url = "https://github.com/carson-drake"
[[params.social]]
   name = "Dont @ me"
   weight = 2
   url = "https://twitter.com/thecarsondrake"
[[params.social]]
    name = "Lets Connect"
    weight = 1
    url = "https://linkedin.com/in/carsondrake"

# Menu links
[[menu.main]]
   name = "Blog"
   weight = 1
   url  = "/posts/"
#[[menu.main]]
#    name = "About"
#    weight = 2
#    url = "/about/"

[[params.navlinks]]
name = "about/"
url = "about/"

[[params.navlinks]]
name = "posts/"
url = "posts/"